version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-network
        #    healthcheck:
        #test: nc -z localhost 3306
        #interval: 2s
        #retries: 3

  back:
    container_name: nestjs-back
    build: 
      context: ./backend
    env_file:
      - .env
    image: nestjs:test
    ports:
      - 3030:3030
    depends_on:
      - db
        #        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - nestjs-network
  
  front:
    container_name: reactjs-front
    build: 
      context: ./frontend
    image: reactjs:test
    ports:
      - 3000:3000
    depends_on:
      - back
    volumes:
      - ./frontend:/app
    networks:
      - nestjs-network

volumes:
  pgdata: {}

networks:
  nestjs-network:
