version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: postgres-db
    environment:
<<<<<<< HEAD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: transcendence
    volumes:
      # - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
=======
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
>>>>>>> b5cbb09eba67d2b70242c9d02e21c07755051dea

  back:
    container_name: nestjs-back
    build: 
      context: ./backend
    env_file:
      - .env
    image: nestjs:test
    ports:
      - 3030:3030
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - nestjs-network
  
  front:
    container_name: reactjs-front
    build: 
      context: ./frontend
    image: reactjs:test
    ports:
      - 3001:3001
    depends_on:
      - back
    volumes:
      - ./frontend:/app
    networks:
      - nestjs-network

volumes:
  pgdata: {}

networks:
  nestjs-network:
