version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: transcendence
    volumes:
      # Cross-platform(m1 mac): uncomment following line
      # - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ft_network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - ft_network

  back:
    container_name: back
    build: 
      context: ./backend
    env_file:
      - .env
      - backend/.env
    image: nestjs:test
    ports:
      - 3030:3030
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - ft_network
  
  front:
    container_name: front
    build: 
      context: ./frontend
    env_file:
      - .env
      - frontend/.env
    image: reactjs:test
    ports:
      - 3001:3001
    # command: sh -c "npm rebuild esbuild"
    # depends_on:
    #   - back
    volumes:
      - ./frontend:/app
    networks:
      - ft_network

volumes:
  pgdata: {}

networks:
  ft_network:
